name: 'my_dbt_project'
version: '0.0.1'
config-version: 2
profile: 'my_dbt_project'
model-paths: ['models']
snapshot-paths: ['snapshots']
test-paths: ['tests']
macro-paths: ['macros']
clean-targets:
  - 'target'
  - 'dbt_packages'
  - 'logs'

